project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "CVEN 5837 - Summer 2022"
  description: "Homepage for Special Topics - Data Analytics for Development"
  site-url: "https://cven5837-ss22.github.io/website/"
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2022, Lars Schöbitz"
    background: "#D9E3E4"
  
  sidebar:
    background: "#D9E3E4"
    logo: "img/logo.png"
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 1
    contents: 
      - href: index.qmd
        text: Course Overview
      - section: "Weekly materials"
        contents: 
          - href: weeks/wk-01.qmd
            text: "Week 1"
          - href: weeks/wk-02.qmd
            text: "Week 2"
          - href: weeks/wk-03.qmd
            text: "Week 3"
        
format:
  html:
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true



