project:
  type: website

website:
  title: "cven5837-ss22"
  
  sidebar:
    background: "#D9E3E4"
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 1
    contents: 
      - href: index.qmd
        text: Course Overview
      - section: "Weekly materials"
        contents: 
          - href: weeks/wk-01.qmd
            text: "Week 1"
        
format:
  html:
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true



